# Generated by Django 6.0.4 on 2026-04-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={},
        ),
    ]
